# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ciff.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ciff.proto',
  package='io.osirrc.ciff',
  syntax='proto3',
  serialized_pb=_b('\n\nciff.proto\x12\x0eio.osirrc.ciff\"$\n\x07Posting\x12\r\n\x05\x64ocid\x18\x01 \x01(\x05\x12\n\n\x02tf\x18\x02 \x01(\x05\"^\n\x0cPostingsList\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\n\n\x02\x64\x66\x18\x02 \x01(\x03\x12\n\n\x02\x63\x66\x18\x03 \x01(\x03\x12(\n\x07posting\x18\x04 \x03(\x0b\x32\x17.io.osirrc.ciff.Postingb\x06proto3')
)




_POSTING = _descriptor.Descriptor(
  name='Posting',
  full_name='io.osirrc.ciff.Posting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='docid', full_name='io.osirrc.ciff.Posting.docid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tf', full_name='io.osirrc.ciff.Posting.tf', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=66,
)


_POSTINGSLIST = _descriptor.Descriptor(
  name='PostingsList',
  full_name='io.osirrc.ciff.PostingsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='io.osirrc.ciff.PostingsList.term', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='df', full_name='io.osirrc.ciff.PostingsList.df', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cf', full_name='io.osirrc.ciff.PostingsList.cf', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='posting', full_name='io.osirrc.ciff.PostingsList.posting', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=162,
)

_POSTINGSLIST.fields_by_name['posting'].message_type = _POSTING
DESCRIPTOR.message_types_by_name['Posting'] = _POSTING
DESCRIPTOR.message_types_by_name['PostingsList'] = _POSTINGSLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Posting = _reflection.GeneratedProtocolMessageType('Posting', (_message.Message,), dict(
  DESCRIPTOR = _POSTING,
  __module__ = 'ciff_pb2'
  # @@protoc_insertion_point(class_scope:io.osirrc.ciff.Posting)
  ))
_sym_db.RegisterMessage(Posting)

PostingsList = _reflection.GeneratedProtocolMessageType('PostingsList', (_message.Message,), dict(
  DESCRIPTOR = _POSTINGSLIST,
  __module__ = 'ciff_pb2'
  # @@protoc_insertion_point(class_scope:io.osirrc.ciff.PostingsList)
  ))
_sym_db.RegisterMessage(PostingsList)


# @@protoc_insertion_point(module_scope)
